# mids zsh config
# exports 
# declare $path
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# oh-my-ZSH vars
#export ZSH="$HOME/.oh-my-zsh"
# if oh-my-zsh installed, source it, otherwise, just setup zsh
#if [[ -f $ZSH/oh-my-zsh.sh ]]; then
#  echo -e "\xE2\x9C\x94 oh-my-zsh.sh exists, sourcing..."
#  source $ZSH/oh-my-zsh.sh
#else
#  echo -e "\xE2\x9C\x94 oh-my-zsh.sh is not present"
#fi
# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
ZSH_THEME="agnoster"
plugins=(
  git
  git-extras
  knife
  osx
  )
# set UTF-8 for sanity
export LANG=en_US.UTF-8
# Tiny Care Terminal variables
export TTC_GITBOT='gitlog'
export TTC_WEATHER='Houston'
export TTC_REPOS='$HOME/src/'
export TTC_APIKEYS=false
export TTC_SAY_BOX='yeoman'
export TTC_CELSIUS=false
export TTC_UPDATE_INTERVAL=5
export TTC_TERMINAL_TITLE=true
export TTC_REPOS_DEPTH=3
# aliases
alias ls="ls -lGFh" # 
alias cd..="cd ../" # Theoretically this will let me navigate backwards
alias ..="cd ../"   # This may be quicker though
alias :q="exit"
# Prefer vim for local / remote editing
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi
# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

## Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"
# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"
# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"
# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="dd.mm.yyyy"
# oh-my-ZSH vars
export ZSH="$HOME/.oh-my-zsh"
# if oh-my-zsh installed, source it, otherwise, just setup zsh
if [[ -f $ZSH/oh-my-zsh.sh ]]; then
  echo -e "\xE2\x9C\x94 oh-my-zsh.sh exists, sourcing..."
  source $ZSH/oh-my-zsh.sh
else
  echo -e "\xE2\x9C\x94 oh-my-zsh.sh is not present"
fi

