#!/bin/sh

# set -ex

# Script for doing some preliminary setup for customizing a terminal environment
# 

usage () {
        echo "$0 [-triage] [-cli] [-home]"
        echo "[----$0----]"
        echo " -triage shells, tmux, vim"
        echo " -cli shells, tmux, vim, git, vundles"
        echo " -home shells, tmux, vim, git, vundles, brew"
        exit 1;
}

if [[ ${#} -eq 0 ]]; then
        usage
fi

shells () {
        echo 'Moving shell configurations'
        cp ../configs/bashprofile $HOME/.bash_profile
        cp ../configs/bashrc $HOME/.bashrc
        cp ../configs/zshrc $HOME/.zshrc
}
# vim install function 
# vim () {
#         echo 'Setting up vim'
#         cp ../configs/vimrc $HOME/.vimrc
#         #  Verify Vundle exists, install if necessary, and upload Vundles in .vimrc
#         if [[ -d "$HOME/.vim/bundle" ]]; then
#         echo 'Vundle folder exists!'
#         sleep 3s
#         vim +PluginInstall +qall
#         echo 'Vundles updated.'
# else    
    
#         echo 'Vundle is not installed! '
#         sleep 10s
#         echo 'Cloning Vundle.vim'  
#         git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
#         sleep 5s
#         echo 'Vundle Installed!'
#         sleep 3s 
#         vim +PluginInstall +qall
#         echo 'Vundles updated.'
# fi

# }


# TODO: Need to properly nest the gitconfigurations for machines - dig into this later between your devices
#
# echo 'Configuring git'  
# if [ -d $HOME/src/fa/ ]; 
#     then
#         echo '/src/fa/ exists! This machine has FA repos'
#         echo 'copying employer git configuration'
#         cp ../configs/gitconfig-fa $HOME/.gitconfig-fa
#         echo 'copying personal git configuration'
#         cp ../configs/gitconfig $HOME/.gitconfig
# else
#         echo ' copying personal git configuation'
#         cp ../configs/gitconfig $HOME/.gitconfig

# fi
echo 'Tmux Config'
cp ../configs/tmux $HOME/.tmux.conf

# echo 'Copying iTerm settings'
# \ this may not be a good idea but might be fixed with profiles at app level \
# cp ../configs/iterm.config $HOME/Library/Preferences/com.googlecode.iterm2.plist

# configure hammerspoon
cp ../configs/hammerspoon $HOME/.hammerspoon/init.lua


source $HOME/.bash_profile
source $HOME/.zshrc
