# This is a basic workflow to help you get started with Actions

name: actions_test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events and maybe has a button?
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-11.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set pf commands to report some info
      - name: debug info
        run: |
					echo $whoami
					echo $PATH
					echo $SHELL
					echo $PWD
					ls -la
